package enumerations;

public enum GroceryCommand {
    ADD, ADDMULTI, DEL, EXP, CAT, AMT, TH, RATE, USE, COST, STORE, LOC, DELLOC,
    LISTLOC, FIND, LIST, LISTCAT, LISTCOST, LISTEXP, EXPIRING, LOW, HELP, SWITCH, REMARK, EXIT

}
