@startuml

participant ":Parser" as p
participant "command:CalCommand" as cal
participant "ui:Ui" as ui
participant "food:Food" as f
participant "userInfo:UserInfo" as info
participant "foodList:foodList" as fl
participant ":System.out" as sys

 -> p : caloriesManagement(commandParts)
create cal
p -> cal : valueOf(commandParts[0].toUpperCase())
cal --> p : command

alt command == EAT
    p -> ui : promptForCalories()
    ui --> p : calories
    create f
    p -> f : Food(commandParts[1],calories)
    f --> p : food
    p -> fl : addFood(food)
    p -> info : consumptionOfCalories(food)
else command == VIEW
    p -> fl: printFoods()
else command == switch
    p -> ui : switchMode()
    ui --> p : currentMode
else command == HELP
    p -> ui : displayHelpForCal()
else command == EXIT
    p -> sys : println("bye bye")
else else
    p -> sys : println(GitException.getMessage())
end



@enduml