@startuml

participant ":Parser" as p
participant "command:ProfileCommand" as prof
participant "profileUi:ProfileUi" as pui
participant "userInfo:UserInfo" as info
participant "ui:Ui" as ui
participant ":System.out" as sys

 -> p : profileManagement(commandParts)
create prof
p -> prof : valueOf(commandParts[0].toUpperCase())
prof --> p : command

alt command == UPDATE
    p -> pui : promptForName()
    pui --> p : name
    p -> pui : promptForWeight()
    pui --> p : Weight
    p -> pui : promptForHeight()
    pui --> p : Height
    p -> pui : promptForAge()
    pui --> p : Age
    p -> pui : promptForGender()
    pui --> p : Gender
    p -> pui : promptForActiveness()
    pui --> p : Activeness
    p -> pui : promptForAim()
    pui --> p : Aim
    p -> info : updateInfo(name, weight,height,age,gender,activeness,aim)
else command == VIEW
    p -> info: viewProfile()
    info --> p : profile
    p -> sys : println(profile)
else command == SWITCH
    p -> ui : switchMode()
    ui --> p : currentMode
else command == HELP
    p -> ui : displayHelpForProf()
else command == EXIT
    p -> sys : println("bye bye")
else else
    p -> sys : println(GitException.getMessage())
end


@enduml