@startuml

participant "groceryList:GroceryList" as gl
participant ":Grocery" as g
participant "ui:Ui" as ui

 -> gl : editAmount()
activate gl

gl -> gl : checkDetails()
note right
Ensures user input is valid
end note
activate gl
return amtParts

gl -> gl : getGrocery()
activate gl
return Grocery

gl -> gl : checkAmount()
note right
Ensures integer is valid
end note
activate gl
return amount

gl -> g : setAmount()
activate g
return

alt finalAmount == 0
    gl -> ui : printAmtDepleted()
    activate ui
    deactivate ui
else else
    gl -> ui : printAmtSet()
    activate ui
    deactivate ui
end

@enduml